name: Deploy on DigitalOceans Droplets
on:
    push:
        branches: [main]

env:
    CONTAINER_NAME: AINewsSummmarization


jobs:
    
    
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        environment: production
        env:
            HOST: ${{secrets.DROPLET_HOST}}
            PASSWORD: ${{secrets.DROPLET_PASSWORD}}
            USERNAME: ${{secrets.DROPLET_USERNAME}}
            PORT: ${{secrets.DROPLET_PORT}}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Test Droplet connection
                uses: appleboy/ssh-action@master
                with:
                    host: ${{env.HOST}}
                    username: ${{env.USERNAME}}
                    password: ${{env.PASSWORD}}
                    port: ${{env.PORT}}
                    script: |
                        docker stop ${{env.CONTAINER_NAME}} || true
                        docker rm -f ${{ env.CONTAINER_NAME }} || true
                        cd AINewsSummarization
                        git fetch origin
                        git checkout main
                        git pull 
                        docker build -t cbctopstories . || true
                        docker run -d --name ${{ env.CONTAINER_NAME }} cbctopstories